"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import os
from setuptools import setup

APP = ['main.py']
DATA_FILES = ['database', 'images', 'gui.ui', 'manhole_logo_en.png', 'map.png', 'manhole_logo_en.icns']
OPTIONS = {'packages': ['PyQt5', 'json', 'webbrowser'], 'iconfile':'manhole_logo_en.icns'}

setup(
    app = APP,
    data_files = DATA_FILES,
    options = {'py2app': OPTIONS},
    setup_requires = ['py2app']
)
